### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

### ISSUE THREAD

**Issue by haitiangege** [kkirchheim/pytorch-ood#1]
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
It seems that it's unreachable for the ood data downloading, is there any question?

**Comment by kkirchheim** [comment]
Hello, this sounds like a connectivity issue on your side. Which dataset are you trying to download? Could you provide a minimal code snippet to reproduce this error?

**Comment by haitiangege** [comment]
Thanks for your replying, it seems that my VPN causing the problem. You did a great job.
