### ISSUE TITLE
ID and OOD samples when inference

### ISSUE THREAD

**Issue by guanhdrmq** [kkirchheim/pytorch-ood#21]
Hi team, when I am trying to use Vilt VQA for AVQA (https://adversarialvqa.org/)test by ViM, but it always gives me the error:

 File "D:\multimodal_robustness\vilt_avqa.py", line 366, in <module>
    print(metrics.compute())
  File "D:\ProgramData\Anaconda3\lib\site-packages\pytorch_ood\utils\metrics.py", line 212, in compute
    #                 raise ValueError("Data must contain IN and OOD samples.")
ValueError: Data must contain IN and OOD samples.

Could you provide a solution? Thank you very much

**Comment by kkirchheim** [comment]
Hi, 

this error is usually raised when the data that you put into the `OODMetrics` object does not contain both IN (label >= 0) and OOD samples (label < 0). For example, it would also be raised if you never called the `update()` method to add some results to your metric. You can find the documentation [here](https://pytorch-ood.readthedocs.io/en/latest/utils.html#pytorch_ood.utils.OODMetrics).
