### ISSUE TITLE
`brightness` is missing in CIFAR10C subsets

### ISSUE THREAD

**Issue by stfwn** [kkirchheim/pytorch-ood#26]
Thanks for providing pytorch-ood!

I noticed a string `brightness` is missing from the list of subsets offered by CIFAR10C. This means the brightness pertubation is not loaded if you attempt to load `all` subsets (the default), and also not if you loop over `CIFAR10C.subsets` to test them individually. This impacts test results.

https://github.com/kkirchheim/pytorch-ood/blob/4a6ef26b824cde6437d68d50aaf98d08ff0cacbd/src/pytorch_ood/dataset/img/cifar.py#L22-L41

**Comment by kkirchheim** [comment]
Thank you for reporting this error. The fix will be included in the next release.
