### ISSUE TITLE
The potential issue in EnergyRegularizedLoss()

### ISSUE THREAD

**Issue by Zhou198** [kkirchheim/pytorch-ood#3]
Hi there,

Thanks for your effort to provide this library. This is a tiny issue in EnergyRegularizedLoss(). The *energy* in the function **_regularization** is not moved to the device since the loss is not specifically designed to deploy to cuda (if any). This is not a big deal, but may not be convenient to implement since the user has to switch back and forth. In contrast, **EntropicOpenSetLoss** is more friendly.

**Comment by kkirchheim** [comment]
Hi, thank you for the feedback. You are right, we will fix this with the next release.
