### ISSUE TITLE
Citation error in [4]

### ISSUE THREAD

**Issue by DanieleAngioni97** [kkirchheim/pytorch-ood#31]
Hey! 
I just noted a citation error in [4] "Dropout as a bayesian approximation: Representing model uncertainty in deep learning".
The authors of this paper are actually Yarin Gal and Zoubin Ghahramani.
Here is the link of the original paper https://proceedings.mlr.press/v48/gal16.pdf

**Comment by kkirchheim** [comment]
Thank you for the report, we fixed it.
