### ISSUE TITLE
Potential issue in OpenMax

### ISSUE THREAD

**Issue by Hummer12007** [kkirchheim/pytorch-ood#4]
Hi, I've noticed that flattened `z` is assigned to the `x` variable and is subsequently unused. 

https://github.com/kkirchheim/pytorch-ood/blob/ced24263dc5db71fa9fd9f753e92536039ce359f/src/pytorch_ood/detector/openmax/torch.py#L78

Is it by design?

**Comment by kkirchheim** [comment]
Hi, no, it is not.  Thank you for noticing.  Will be fixed, but the bug should not influence the result, since the z should be flattened anyway.

**Comment by kkirchheim** [comment]
This has been fixed with 6db557b
